### ISSUE TITLE
multiline cell

### ISSUE THREAD

**Issue by vruzin** [tolik505/split-csv#5]
if we have:
```
"id";"name";"text"
"1222223";"тест";"Шла
Маша
по
шоссе"
123;Петя;Во какой
```

**Comment by tolik505** [comment]
It works fine if the multiline cell is not between 2 chunks. Otherwise, it divides the cell.
Going to fix the case.

**Comment by vruzin** [comment]
Thank you!

**Comment by tolik505** [comment]
The support of multiline cells is added in v1.2.0
