### ISSUE TITLE
Unexpected header and unexpected split files

### ISSUE THREAD

**Issue by DingYuan0118** [tolik505/split-csv#9]
Found a bug.
If `spliter.bufferSize < len(header)`. the field `st.columnsCount` will not be initialized correctly by `countCompletedColumns`  causes `st.header` is unexpected and generate unexpected files

**Comment by DingYuan0118** [comment]
reproduce: fix the `spliter.bufferSize=10` and split a file whose header is larger than 10 bytes

**Comment by tolik505** [comment]
This case is a super edge-case.
Buffer size is os.Getpagesize() * 128. Typically, memory page size is 4KB, and after multiplying we get 0.5MB. Which is more than enough for the header.

Do you really have a csv file with a header > 0.5 MB?
